- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Copying the configuration file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: remove the old directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create a app directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download the app content
  ansibel.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Start and enable nginx serivce
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes