- name: Ensuring the application system user present
  ansible.builtin.user:
    name: "{{nodejs_app_user}}"

- name: Removing the existing /app directory to clean up old cache
  ansible.builtin.file:
    path: /app
    state: absent

- name: Recreating /app directory for application
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download application artifact
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{service}}.zip
    dest: /app
    remote_src: yes